version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root1234"
    volumes:
      - ./hi:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    image: apimage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 80:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root1234
    links:
      - db
    restart: always
